export const MOCK_SCHEMES = [
  { 
    id: 1, 
    title: "PM KISAN Samman Nidhi", 
    description: "Financial benefit of ₹6000 per year to small and marginal farmer families",
    ministry: "Ministry of Agriculture",
    category: "Farmers",
    benefits: "₹6000 per year in three installments",
    eligibility: "Small and marginal farmers with landholding",
    documents: ["Land papers", "Aadhar card", "Bank account"],
    applyLink: "https://pmkisan.gov.in",
    occupations: ["farmer"]
  },
  { 
    id: 2, 
    title: "National Scholarship Portal", 
    description: "Central Sector Scholarship for meritorious students",
    ministry: "Ministry of Education",
    category: "Students",
    benefits: "₹10,000 to ₹50,000 per year",
    eligibility: "Students with >60% marks, family income < ₹6 lakhs",
    documents: ["Marksheets", "Income certificate", "Bank details"],
    applyLink: "https://scholarships.gov.in",
    occupations: ["student"]
  },
  { 
    id: 3, 
    title: "PM Mudra Yojana", 
    description: "Loans up to ₹10 lakh for small businesses and entrepreneurs",
    ministry: "Ministry of Finance",
    category: "Business",
    benefits: "Collateral-free loans under Shishu, Kishor, Tarun",
    eligibility: "Small business owners, entrepreneurs, startups",
    documents: ["Business plan", "Identity proof", "Address proof"],
    applyLink: "https://mudra.org.in",
    occupations: ["entrepreneur"]
  },
  { 
    id: 4, 
    title: "Ayushman Bharat Scheme", 
    description: "Health insurance cover of ₹5 lakh per family",
    ministry: "Ministry of Health",
    category: "Health",
    benefits: "₹5 lakh per family per year",
    eligibility: "SECC database identified families",
    documents: ["Aadhar", "Ration card", "SECC ID"],
    applyLink: "https://pmjay.gov.in",
    occupations: ["health", "senior", "women"]
  },
  { 
    id: 5, 
    title: "Sukanya Samriddhi Yojana", 
    description: "Savings scheme for girl child education and marriage",
    ministry: "Ministry of Finance",
    category: "Women",
    benefits: "7.6% interest rate, tax benefits",
    eligibility: "Parents of girl child below 10 years",
    documents: ["Girl's birth certificate", "Parent's ID"],
    applyLink: "https://www.indiapost.gov.in",
    occupations: ["woman"]
  },
  { 
    id: 6, 
    title: "PM Surya Ghar Muft Bijli Yojana", 
    description: "Free electricity through rooftop solar panels with government subsidy",
    ministry: "Ministry of New & Renewable Energy",
    category: "Solar Energy",
    benefits: "Up to ₹78,000 subsidy for solar panel installation + Housing loan at 3% interest",
    eligibility: "Homeowners with suitable rooftop space",
    documents: ["Property papers", "Aadhar card", "Electricity bill", "Bank account"],
    applicationProcess: "Apply at nearest bank or through national portal",
    applyLink: "https://pmsuryaghar.gov.in",
    occupations: ["solar", "housing"]
  },
  { 
    id: 7, 
    title: "PM Awas Yojana", 
    description: "Housing for all - Financial assistance for home construction",
    ministry: "Ministry of Housing",
    category: "Housing",
    benefits: "Interest subsidy up to ₹2.67 lakh on home loan",
    eligibility: "EWS/LIG/MIG categories",
    documents: ["Aadhar", "Income certificate", "Bank statement"],
    applyLink: "https://pmaymis.gov.in",
    occupations: ["housing", "senior", "scst"]
  },
  { 
    id: 8, 
    title: "Stand-Up India Scheme", 
    description: "Loans for SC/ST and women entrepreneurs",
    ministry: "Ministry of Finance",
    category: "Business",
    benefits: "₹10 lakh to ₹1 crore",
    eligibility: "SC/ST and Women entrepreneurs",
    documents: ["Business plan", "Caste certificate", "Identity proof"],
    applyLink: "https://standupmitra.in",
    occupations: ["entrepreneur", "scst", "woman"]
  },
  { 
    id: 9, 
    title: "National Pension Scheme", 
    description: "Social security for senior citizens",
    ministry: "Ministry of Social Justice",
    category: "Senior Citizens",
    benefits: "Monthly pension of ₹200-500",
    eligibility: "Above 60 years, BPL families",
    documents: ["Age proof", "BPL certificate", "Bank passbook"],
    applyLink: "https://socialjustice.gov.in",
    occupations: ["senior"]
  },
  { 
    id: 10, 
    title: "Pradhan Mantri Matru Vandana Yojana",
    description: "Maternity benefit scheme for pregnant and lactating mothers",
    ministry: "Ministry of Women & Child Development",
    category: "Women",
    benefits: "₹5,000 cash transfer for first child",
    eligibility: "Pregnant women of age 19+",
    documents: ["Maternity card", "Aadhar", "Bank account"],
    applyLink: "https://wcd.nic.in",
    occupations: ["woman"]
  },
  { 
    id: 11, 
    title: "SC/ST Post-Matric Scholarship",
    description: "Financial assistance for SC/ST students for higher education",
    ministry: "Ministry of Social Justice",
    category: "SC/ST",
    benefits: "Full tuition fees + maintenance allowance",
    eligibility: "SC/ST students with family income < ₹2.5 lakhs",
    documents: ["Caste certificate", "Income certificate", "Marksheets"],
    applyLink: "https://scholarships.gov.in",
    occupations: ["scst", "student"]
  },
  { 
    id: 12, 
    title: "Startup India Scheme",
    description: "Government support for startups and entrepreneurs",
    ministry: "Ministry of Commerce & Industry",
    category: "Business",
    benefits: "Tax exemption, funding support, mentoring",
    eligibility: "Registered startups in India",
    documents: ["Incorporation certificate", "Business plan", "PAN card"],
    applyLink: "https://www.startupindia.gov.in",
    occupations: ["entrepreneur"]
  },
  { 
    id: 13, 
    title: "Khelo India Scheme",
    description: "Sports development and athlete support program",
    ministry: "Ministry of Sports",
    category: "Sports",
    benefits: "Financial assistance, training, and competition support",
    eligibility: "Promising athletes across India",
    documents: ["Sports certificate", "Age proof", "Bank account"],
    applyLink: "https://kheloindia.gov.in",
    occupations: ["sports"]
  },
  { 
    id: 14, 
    title: "Ex-Serviceman Contributory Health Scheme",
    description: "Health insurance for ex-servicemen and their families",
    ministry: "Ministry of Defence",
    category: "Defence",
    benefits: "OPD and hospitalization coverage",
    eligibility: "Ex-servicemen and dependent family members",
    documents: ["Service discharge book", "Aadhar card"],
    applyLink: "https://mod.gov.in",
    occupations: ["exserviceman"]
  },
  { 
    id: 15, 
    title: "Solar Rooftop Loan Scheme",
    description: "Special housing loan with 3% interest for solar panel installation",
    ministry: "Ministry of Power",
    category: "Solar Energy",
    benefits: "Low interest loan + Government subsidy on solar panels",
    eligibility: "Homeowners with valid property documents",
    documents: ["Property papers", "Electricity bill", "Income proof"],
    applicationProcess: "Apply through SBI, PNB, or other nationalized banks",
    applyLink: "https://pmsuryaghar.gov.in",
    occupations: ["solar", "housing"]
  }
];